const fs = require("fs");
const path = require("path");

// Configuration
const BASE_IMAGES_DIR = path.join(__dirname, "..", "public", "images"); // Assuming images are in public/images
const OUTPUT_DIR = path.join(__dirname, "..", "src", "data"); // Output to src/data
const FOLDERS_TO_SCAN = ["animals", "baseball", "pokemon"];
const FILE_EXTENSIONS = [".png", ".jpg", ".jpeg", ".webp"];

// Ensure the output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

FOLDERS_TO_SCAN.forEach((folderName) => {
  const folderPath = path.join(BASE_IMAGES_DIR, folderName);
  const variableName = `${folderName}Images`; // e.g., animalImages

  // 1. Scan the directory
  try {
    const files = fs.readdirSync(folderPath);

    // 2. Filter for image files and format paths
    const imagePaths = files
      .filter((file) =>
        FILE_EXTENSIONS.includes(path.extname(file).toLowerCase())
      )
      .map((file) => {
        // Create the public-facing path, e.g., "./images/animals/file.png"
        return `"./images/${folderName}/${file}"`;
      });

    // 3. Create file content string
    const fileContent = `
// NOTE: This file is auto-generated by a script. Do not modify manually.
export const ${variableName} = [
  ${imagePaths.join(',\n  ')}
];
`;

    // 4. Write the file
    const outputFilePath = path.join(OUTPUT_DIR, `${folderName}.js`);
    fs.writeFileSync(outputFilePath, fileContent.trim());

    console.log(
      `✅ Generated ${outputFilePath} with ${imagePaths.length} image paths.`
    );
  } catch (error) {
    console.error(`❌ Could not scan folder ${folderPath}. Does it exist?`);
    // console.error(error); // Uncomment for detailed error
  }
});